# Generated by Django 3.0.7 on 2020-07-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200716_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
